Repository googleapis/nodejs-contact-center-insights, pull requests merged in 2021-07, with the labels that each got.

#2 feat: add initial samples
  .github/.OwlBot.lock.yaml
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/workflows/ci.yaml
  .kokoro/common.cfg
  .kokoro/continuous/node10/common.cfg
  .kokoro/continuous/node10/docs.cfg
  .kokoro/continuous/node12/common.cfg
  .kokoro/continuous/node12/lint.cfg
  .kokoro/continuous/node12/samples-test.cfg
  .kokoro/continuous/node12/system-test.cfg
  .kokoro/presubmit/node10/common.cfg
  .kokoro/presubmit/node12/common.cfg
  .kokoro/presubmit/node12/samples-test.cfg
  .kokoro/presubmit/node12/system-test.cfg
  .kokoro/release/docs-devsite.cfg
  .kokoro/release/docs.cfg
  .kokoro/release/publish.cfg
  .kokoro/test.sh
  README.md
  linkinator.config.json
  package.json
  samples/README.md
  samples/quickstart.js
  samples/test/quickstart.js
  src/v1/contact_center_insights_client.ts
  system-test/fixtures/sample/src/index.js
  system-test/fixtures/sample/src/index.ts
Labels: api: contactcenterinsights, cla: yes, samples

#6 fix(deps): google-gax v2.17.0 with mTLS
  package.json
Labels: api: contactcenterinsights, cla: yes, owlbot:run

#11 fix(deps): google-gax v2.17.1
  package.json
Labels: api: contactcenterinsights, automerge, cla: yes
